sync-config:
  naocs:
    addr: http://127.0.0.1:8081
    url: http://127.0.0.1:8081/nacos
    group: dev
    namespace: nacos-test
    file-extension: yml
    loginUrl: http://127.0.0.1:8081/nacos/v1/auth/users/login
    configUrl: http://127.0.0.1:8081/nacos/v1/cs/configs
    username: ${nacos_username}
    password: ${nacos_password}
  gitlab:
    branch: dev