sync-config:
  config-addr: /tmp
  naocs:
    addr: http://127.0.0.1:8081
    url: http://127.0.0.1:8081/nacos
    group: dev
    namespace: nacos-test
    file-extension: yml
    loginUrl: http://127.0.0.1:8081/nacos/v1/auth/users/login
    configUrl: http://127.0.0.1:8081/nacos/v1/cs/configs
    username: nacos
    password: nacos
  gitlab:
    branch: dev
  envs: "
   baseUrl: 127.0.0.1:8081


    "
